services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: leawaretest
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    api:
        build:
            dockerfile: ./LeawareTest.API/Dockerfile
        environment:
            - ConnectionStrings__DefaultConnection=server=db;database=leawaretest;user=root;password=root
            - EmailSettings__Username=leawaretestpp@op.pl
                - EmailSettings__Password=ZH35-W0IU-TLLS-NFZY
                - EmailSettings__Host=imap.poczta.onet.pl
                - OpenAISettings__ApiKey=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
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - db

    app:
        build:
            dockerfile: ./LeawareTest.Blazor/Dockerfile
        environment:
            - ASPNETCORE_URLS=http://+:5096
            - DOTNET_RUNNING_IN_CONTAINER=true
            - ASPNETCORE_ENVIRONMENT=Development
            - Api__BaseAddress=http://api:8080
        ports:
            - "5096:5096"
        depends_on:
            - api
volumes:
    db_data:

